# Generated by Django 4.1.2 on 2022-10-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('adorable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharks.species')),
            ],
        ),
    ]
